set global log_bin_trust_function_creators=1;

show DATABASES;
use kodilla_course;

CREATE TABLE BOOKS (

                       BOOK_ID int(11) NOT NULL AUTO_INCREMENT,
                       TITLE varchar(255) NOT NULL,
                       PUBYEAR int(4) NOT NULL,
                       PRIMARY KEY (BOOK_ID)
);

CREATE TABLE READERS (
                         READER_ID int(11) NOT NULL AUTO_INCREMENT,
                         FIRSTNAME varchar(255) NOT NULL,
                         LASTNAME varchar(255) NOT NULL,
                         PESELID varchar(11) NOT NULL,
                         PRIMARY KEY (READER_ID)
);

CREATE TABLE RENTS (
                       RENT_ID int(11) NOT NULL AUTO_INCREMENT,
                       BOOK_ID int(11) NOT NULL,
                       READER_ID int(11) NOT NULL,
                       RENT_DATE datetime NOT NULL,
                       RETURN_DATE datetime,
                       PRIMARY KEY (RENT_ID),
                       FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID),
                       FOREIGN KEY (READER_ID) REFERENCES READERS(READER_ID)
);

INSERT INTO READERS(FIRSTNAME, LASTNAME, PESELID)
VALUES ("John", "Smith", "83012217938");

INSERT INTO READERS(FIRSTNAME, LASTNAME, PESELID)
VALUES ("Curtis", "Wilson", "75121002790");

INSERT INTO READERS(FIRSTNAME, LASTNAME, PESELID)
VALUES ("Cathy", "Booker", "90112801727");

INSERT INTO READERS(FIRSTNAME, LASTNAME, PESELID)
VALUES ("Marissa", "Cain", "84061908044");

INSERT INTO READERS(FIRSTNAME, LASTNAME, PESELID)
VALUES ("Muriel", "Fulton", "76081409269");

COMMIT;

INSERT INTO BOOKS(TITLE, PUBYEAR)
VALUES ("The Stranger", 1942);

INSERT INTO BOOKS(TITLE, PUBYEAR)
VALUES ("In Search of Lost Time", 1927);

INSERT INTO BOOKS(TITLE, PUBYEAR)
VALUES ("The Trial", 1925);

INSERT INTO BOOKS(TITLE, PUBYEAR)
VALUES ("The Little Prince", 1943);

INSERT INTO BOOKS(TITLE, PUBYEAR)
VALUES ("Man's Fate", 1933);

COMMIT;

INSERT INTO RENTS(BOOK_ID, READER_ID, RENT_DATE, RETURN_DATE)
VALUES (1, 1, DATE_SUB(CURDATE(), INTERVAL 10 DAY), null);

INSERT INTO RENTS(BOOK_ID, READER_ID, RENT_DATE, RETURN_DATE)
VALUES (2, 1, DATE_SUB(CURDATE(), INTERVAL 10 DAY), null);

INSERT INTO RENTS(BOOK_ID, READER_ID, RENT_DATE, RETURN_DATE)
VALUES (4, 1, DATE_SUB(CURDATE(), INTERVAL 10 DAY), DATE_SUB(CURDATE(), INTERVAL 5 DAY));

INSERT INTO RENTS(BOOK_ID, READER_ID, RENT_DATE, RETURN_DATE)
VALUES (1, 3, DATE_SUB(CURDATE(), INTERVAL 8 DAY), null);

INSERT INTO RENTS(BOOK_ID, READER_ID, RENT_DATE, RETURN_DATE)
VALUES (5, 3, DATE_SUB(CURDATE(), INTERVAL 4 DAY), DATE_SUB(CURDATE(), INTERVAL 2 DAY));

INSERT INTO RENTS(BOOK_ID, READER_ID, RENT_DATE, RETURN_DATE)
VALUES (5, 4, DATE_SUB(CURDATE(), INTERVAL 10 DAY), DATE_SUB(CURDATE(), INTERVAL 8 DAY));

INSERT INTO RENTS(BOOK_ID, READER_ID, RENT_DATE, RETURN_DATE)
VALUES (5, 5, DATE_SUB(CURDATE(), INTERVAL 8 DAY), null);

COMMIT;

DELIMITER $$

CREATE PROCEDURE ListBooks()
BEGIN
    SELECT * FROM BOOKS;
END $$

DELIMITER ;

DROP PROCEDURE IF EXISTS ListBooks;

DELIMITER $$

CREATE PROCEDURE ListBooks()
BEGIN
    SELECT BOOK_ID, TITLE, PUBYEAR FROM BOOKS;
END $$

DELIMITER ;

CALL ListBooks();

DROP FUNCTION IF EXISTS VipLevel;

DELIMITER $$

CREATE FUNCTION VipLevel() RETURNS VARCHAR(20) DETERMINISTIC
BEGIN
    RETURN 'Standard customer';
END $$

DELIMITER ;

SELECT VipLevel() AS LEVEL;


DROP FUNCTION IF EXISTS VipLevel;

DELIMITER $$

CREATE FUNCTION VipLevel(booksrented INT) RETURNS VARCHAR(20) DETERMINISTIC -- [1]
BEGIN									                                    -- [2]
    DECLARE result VARCHAR(20) DEFAULT 'Standard customer';	                -- [3]
    IF booksrented >= 10 THEN						                        -- [4]
        SET result = 'Gold customer';					                        -- [5]
    ELSEIF booksrented >= 5 AND booksrented < 10 THEN			            -- [6]
        SET result = 'Silver customer';				                        -- [7]
    ELSEIF booksrented >= 2 AND booksrented < 5 THEN			            -- [8]
        SET result = 'Bronze customer';		           		                -- [9]
    ELSE				      					                                -- [10]
        SET result = 'Standard customer';				                        -- [11]
    END IF;				    				                                -- [12]
    RETURN result;
END $$

DELIMITER ;

SELECT VipLevel(12) AS LEVEL;


DROP FUNCTION IF EXISTS GetUserNameById;

DELIMITER $$

CREATE PROCEDURE GetUserNameById(IN user_id INT)
BEGIN
    IF user_id <= 0 THEN
        SELECT 'Bad ID' AS komunikat;
    ELSE
        SELECT FIRSTNAME
        FROM users
        WHERE id = user_id;
    END IF;
END $$

DELIMITER ;

CALL GetUserNameById(1);

CALL GetUserNameById(-3);


ALTER TABLE READERS ADD VIP_LEVEL VARCHAR(20);

DROP PROCEDURE IF EXISTS UpdateVipLevels;

DELIMITER $$

CREATE PROCEDURE UpdateVipLevels()
BEGIN
    DECLARE BOOKSREAD INT;

    SELECT COUNT(*) FROM RENTS
    WHERE READER_ID = 3
    INTO BOOKSREAD;

    SELECT BOOKSREAD;
END $$

DELIMITER ;


DROP PROCEDURE IF EXISTS UpdateVipLevels;

DELIMITER $$

CREATE PROCEDURE UpdateVipLevels()
BEGIN
    DECLARE BOOKSREAD INT;
    DECLARE DAYS INT;
    DECLARE BOOKSPERMONTH DECIMAL(5,2);

    SELECT COUNT(*) FROM RENTS
    WHERE READER_ID = 3
    INTO BOOKSREAD;

    SELECT DATEDIFF(MAX(RENT_DATE), MIN(RENT_DATE)) + 1 FROM RENTS -- [1]
    WHERE READER_ID = 3	                                  -- [2]
    INTO DAYS;                                           -- [3]

    SET BOOKSPERMONTH = BOOKSREAD / DAYS * 30;                 -- [4]

    SELECT BOOKSREAD, DAYS, BOOKSPERMONTH;                     -- [5]
END $$

DELIMITER ;

CALL UpdateVipLevels();




DROP PROCEDURE IF EXISTS UpdateVipLevels;

DELIMITER $$

CREATE PROCEDURE UpdateVipLevels()
BEGIN
    DECLARE BOOKSREAD, DAYS, RDR_ID INT;				 -- [1]
    DECLARE BOOKSPERMONTH DECIMAL(5,2);				 -- [2]
    DECLARE FINISHED INT DEFAULT 0;			   	     -- [3]
    DECLARE ALL_READERS CURSOR FOR SELECT READER_ID FROM READERS;        -- [4]
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET FINISHED = 1;	            -- [5]
    OPEN ALL_READERS;			   		         	 -- [6]
    WHILE (FINISHED = 0) DO			   		         -- [7]
    FETCH ALL_READERS INTO RDR_ID;			   	 -- [8]
    IF (FINISHED = 0) THEN			   		     -- [9]
        SELECT COUNT(*) FROM RENTS			   	     -- [10]
        WHERE READER_ID = RDR_ID			     -- [11]
        INTO BOOKSREAD;			   		     -- [12]

        SELECT DATEDIFF(MAX(RENT_DATE), MIN(RENT_DATE)) + 1 FROM RENTS -- [13]
        WHERE READER_ID = RDR_ID                           		    -- [14]
        INTO DAYS;                                       	    -- [15]

        SET BOOKSPERMONTH = BOOKSREAD / DAYS * 30;              	    -- [16]

        UPDATE READERS SET VIP_LEVEL = VipLevel(BOOKSPERMONTH)		    -- [17]
        WHERE READER_ID = RDR_ID;			   		                -- [18]
        COMMIT;			   				                            -- [19]
    END IF;			   					                            -- [20]
        END WHILE;			   					                            -- [21]

    CLOSE ALL_READERS;   			   			                        -- [22]
END $$

DELIMITER ;

CALL UpdateVipLevels();

SELECT * FROM READERS;


-- zadanie

ALTER TABLE BOOKS
    ADD COLUMN BESTSELLER BOOLEAN NOT NULL DEFAULT 0;

DELIMITER $$

CREATE PROCEDURE UpdateBestsellers()
BEGIN
    DECLARE DONE INT DEFAULT 0;
    DECLARE CURRENT_BOOK_ID INT;
    DECLARE TOTAL_RENTS INT;
    DECLARE RENT_DAYS INT;
    DECLARE BOOKS_PER_MONTH DECIMAL(5,2);

    DECLARE BOOKS_CURSOR CURSOR FOR SELECT BOOK_ID FROM BOOKS;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = 1;

    UPDATE BOOKS SET BESTSELLER = 0 WHERE BOOK_ID > 0;
    COMMIT;

    OPEN BOOKS_CURSOR;

    READ_LOOP: LOOP
        FETCH BOOKS_CURSOR INTO CURRENT_BOOK_ID;

        IF DONE THEN
            LEAVE READ_LOOP;
        END IF;

        SELECT COUNT(*) INTO TOTAL_RENTS
        FROM RENTS
        WHERE BOOK_ID = CURRENT_BOOK_ID;

        IF TOTAL_RENTS = 0 THEN
            SET BOOKS_PER_MONTH = 0;
        ELSE
            SELECT DATEDIFF(MAX(RENT_DATE), MIN(RENT_DATE)) + 1
            INTO RENT_DAYS
            FROM RENTS
            WHERE BOOK_ID = CURRENT_BOOK_ID;

            SET BOOKS_PER_MONTH = (TOTAL_RENTS / RENT_DAYS) * 30;
        END IF;

        UPDATE BOOKS
        SET BESTSELLER = IF(BOOKS_PER_MONTH > 2, TRUE, FALSE)
        WHERE BOOK_ID = CURRENT_BOOK_ID;

    END LOOP;

    CLOSE BOOKS_CURSOR;
    COMMIT;
END $$

DELIMITER ;

CALL UpdateBestsellers();

SELECT * FROM BOOKS;


SET @RENTSQTY = 0;                                 -- [1]

DELIMITER $$

CREATE TRIGGER RENTSCOUNTER BEFORE INSERT ON RENTS -- [2]
    FOR EACH ROW
BEGIN
    SET @RENTSQTY = @RENTSQTY + 1;                  -- [3]
END $$

DELIMITER ;


INSERT INTO RENTS(BOOK_ID, READER_ID, RENT_DATE, RETURN_DATE)
VALUES(1, 3, DATE_SUB(CURDATE(), INTERVAL 5 DAY), NULL);

INSERT INTO RENTS(BOOK_ID, READER_ID, RENT_DATE, RETURN_DATE)
VALUES(2, 3, DATE_SUB(CURDATE(), INTERVAL 2 DAY), NULL);

INSERT INTO RENTS(BOOK_ID, READER_ID, RENT_DATE, RETURN_DATE)
VALUES(3, 1, DATE_SUB(CURDATE(), INTERVAL 5 DAY), NULL);

INSERT INTO RENTS(BOOK_ID, READER_ID, RENT_DATE, RETURN_DATE)
VALUES(2, 4, DATE_SUB(CURDATE(), INTERVAL 3 DAY), NULL);

COMMIT;

SELECT @RENTSQTY;

DROP TRIGGER RENTSCOUNTER;


CREATE TABLE RENTS_AUD (
                           EVENT_ID INT(11) NOT NULL AUTO_INCREMENT,
                           EVENT_DATE DATETIME NOT NULL,
                           EVENT_TYPE VARCHAR(10) DEFAULT NULL,
                           RENT_ID INT(11) NOT NULL,
                           OLD_BOOK_ID INT(11),
                           NEW_BOOK_ID INT(11),
                           OLD_READER_ID INT(11),
                           NEW_READER_ID INT(11),
                           OLD_RENT_DATE DATETIME,
                           NEW_RENT_DATE DATETIME,
                           OLD_RETURN_DATE DATETIME,
                           NEW_RETURN_DATE DATETIME,
                           PRIMARY KEY (EVENT_ID)
);

DELIMITER $$

CREATE TRIGGER RENTS_INSERT AFTER INSERT ON RENTS                                        -- [1]
    FOR EACH ROW
BEGIN
    INSERT INTO RENTS_AUD (EVENT_DATE, EVENT_TYPE, RENT_ID, NEW_BOOK_ID, NEW_READER_ID,   -- [2]
                           NEW_RENT_DATE, NEW_RETURN_DATE)                                -- [3]
        VALUE(CURTIME(), 'INSERT', NEW.RENT_ID, NEW.BOOK_ID, NEW.READER_ID, NEW.RENT_DATE, -- [4]
              NEW.RETURN_DATE);                                                            -- [5]
END $$

DELIMITER ;


INSERT INTO RENTS (BOOK_ID, READER_ID, RENT_DATE, RETURN_DATE)
VALUES (2, 4, DATE_SUB(CURDATE(), INTERVAL 5 DAY), NULL);

COMMIT;

SELECT * FROM RENTS_AUD;


DELIMITER $$

CREATE TRIGGER RENTS_DELETE AFTER DELETE ON RENTS          -- [1]
    FOR EACH ROW
BEGIN
    INSERT INTO RENTS_AUD (EVENT_DATE, EVENT_TYPE, RENT_ID) -- [2]
        VALUE(CURTIME(), 'DELETE', OLD.RENT_ID);             -- [3]
END $$

DELIMITER ;

SELECT * FROM RENTS;

DELETE FROM RENTS WHERE RENT_ID = 12;

COMMIT;


DELIMITER $$

CREATE TRIGGER RENTS_UPDATE AFTER UPDATE ON RENTS
    FOR EACH ROW
BEGIN
    INSERT INTO RENTS_AUD (EVENT_DATE, EVENT_TYPE, RENT_ID, NEW_BOOK_ID, NEW_READER_ID,
                           NEW_RENT_DATE, NEW_RETURN_DATE, OLD_BOOK_ID, OLD_READER_ID,
                           OLD_RENT_DATE, OLD_RETURN_DATE)
        VALUE(CURTIME(), 'UPDATE', OLD.RENT_ID, NEW.BOOK_ID, NEW.READER_ID,
              NEW.RENT_DATE, NEW.RETURN_DATE, OLD.BOOK_ID, OLD.READER_ID,
              OLD.RENT_DATE, OLD.RETURN_DATE);
END $$

DELIMITER ;

UPDATE RENTS SET RETURN_DATE = CURDATE()
WHERE RENT_ID = 11;

COMMIT;

-- zadanie 28.4.

-- BOOKS_AUD
CREATE TABLE BOOKS_AUD (
                           EVENT_ID INT(11) NOT NULL AUTO_INCREMENT,
                           EVENT_DATE DATETIME NOT NULL,
                           EVENT_TYPE VARCHAR(10) DEFAULT NULL,
                           BOOK_ID INT(11) NOT NULL,
                           OLD_TITLE VARCHAR(250) DEFAULT NULL,
                           NEW_TITLE VARCHAR(250) DEFAULT NULL,
                           OLD_PUBLICATION_YEAR INT(11),
                           NEW_PUBLICATION_YEAR INT(11),
                           OLD_BESTSELLER TINYINT(1),
                           NEW_BESTSELLER TINYINT(1),
                           PRIMARY KEY (EVENT_ID)
);

-- INSERT

DELIMITER $$

CREATE TRIGGER BOOKS_INSERT AFTER INSERT ON BOOKS                                        -- [1]
    FOR EACH ROW
BEGIN
    INSERT INTO BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID,NEW_TITLE,
                           NEW_PUBLICATION_YEAR, NEW_BESTSELLER)                                -- [3]
        VALUE(CURTIME(), 'INSERT', NEW.BOOK_ID,
              NEW.TITLE, NEW.PUBYEAR,
              NEW.BESTSELLER);                                                            -- [5]
END $$

DELIMITER ;


INSERT INTO BOOKS (TITLE,PUBYEAR,BESTSELLER)
VALUES ('Teoria betonu',1993,0);

COMMIT;

SELECT * FROM BOOKS_AUD;

-- delete

DELIMITER $$

CREATE TRIGGER BOOKS_DELETE AFTER DELETE ON BOOKS          -- [1]
    FOR EACH ROW
BEGIN
    INSERT INTO BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID) -- [2]
        VALUE(CURTIME(), 'DELETE', OLD.BOOK_ID);             -- [3]
END $$

DELIMITER ;

SELECT * FROM BOOKS;

DELETE FROM BOOKS WHERE books.BOOK_ID = 6;

COMMIT;

SELECT * FROM BOOKS_AUD;

-- update

DELIMITER $$

CREATE TRIGGER BOOKS_UPDATE AFTER UPDATE ON BOOKS
    FOR EACH ROW
BEGIN
    INSERT INTO BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID,OLD_TITLE,NEW_TITLE,OLD_PUBLICATION_YEAR,NEW_PUBLICATION_YEAR,OLD_BESTSELLER,NEW_BESTSELLER)
        VALUE(CURTIME(), 'UPDATE', BOOK_ID,OLD.TITLE,
              NEW.TITLE,OLD.PUBYEAR,
              NEW.PUBYEAR,OLD.BESTSELLER,
              NEW.BESTSELLER);
END $$

DELIMITER ;

UPDATE BOOKS SET TITLE = 'Teoria wielkiego betonu'
WHERE books.BOOK_ID = 7;

COMMIT;

SELECT * FROM BOOKS_AUD;

-- READERS_AUD

CREATE TABLE READERS_AUD (
                           EVENT_ID INT(11) NOT NULL AUTO_INCREMENT,
                           EVENT_DATE DATETIME NOT NULL,
                           EVENT_TYPE VARCHAR(10) DEFAULT NULL,
                           READER_ID INT(11) NOT NULL,
                           OLD_FIRSTNAME VARCHAR(250) DEFAULT NULL,
                           NEW_FIRSTNAME VARCHAR(250) DEFAULT NULL,
                           OLD_LASTNAME VARCHAR(250) DEFAULT NULL,
                           NEW_LASTNAME VARCHAR(250) DEFAULT NULL,
                           OLD_PESEL_ID VARCHAR(25) DEFAULT NULL,
                           NEW_PESEL_ID VARCHAR(25) DEFAULT NULL,
                           OLD_VIP_LEVEL VARCHAR(25) DEFAULT NULL,
                           NEW_VIP_LEVEL VARCHAR(25) DEFAULT NULL,
                           PRIMARY KEY (EVENT_ID)
);

-- INSERT

DELIMITER $$

CREATE TRIGGER READERS_INSERT AFTER INSERT ON READERS                                        -- [1]
    FOR EACH ROW
BEGIN
    INSERT INTO READERS_AUD (EVENT_DATE, EVENT_TYPE, READER_ID,NEW_FIRSTNAME,NEW_LASTNAME,NEW_PESEL_ID,NEW_VIP_LEVEL)                                -- [3]
        VALUE(CURTIME(), 'INSERT', READER_ID,NEW.FIRSTNAME,NEW.LASTNAME,NEW.PESELID,NEW.VIP_LEVEL);                                                            -- [5]
END $$

DELIMITER ;


INSERT INTO READERS (FIRSTNAME,LASTNAME,PESELID,VIP_LEVEL)
VALUES ('Merlin','Monrou','83031811280','0');

COMMIT;

SELECT * FROM READERS_AUD;

-- delete

DELIMITER $$

CREATE TRIGGER READERS_DELETE AFTER DELETE ON READERS          -- [1]
    FOR EACH ROW
BEGIN
    INSERT INTO READERS_AUD (EVENT_DATE, EVENT_TYPE, READER_ID) -- [2]
        VALUE(CURTIME(), 'DELETE', OLD.READER_ID);             -- [3]
END $$

DELIMITER ;

SELECT * FROM READERS;

DELETE FROM READERS WHERE READERS.READER_ID = 8;

COMMIT;

SELECT * FROM READERS_AUD;

-- update

DELIMITER $$

CREATE TRIGGER READERS_UPDATE AFTER UPDATE ON READERS
    FOR EACH ROW
BEGIN
    INSERT INTO READERS_AUD (EVENT_DATE, EVENT_TYPE, READER_ID,OLD_FIRSTNAME,NEW_FIRSTNAME,OLD_LASTNAME,NEW_LASTNAME,
                             OLD_PESEL_ID,NEW_PESEL_ID,OLD_VIP_LEVEL,NEW_VIP_LEVEL)
        VALUE(CURTIME(), 'UPDATE', READER_ID,OLD.FIRSTNAME,
              NEW.FIRSTNAME,OLD.LASTNAME,NEW.LASTNAME,
              OLD.PESELID,NEW.PESELID,OLD.VIP_LEVEL,
              NEW.VIP_LEVEL);
END $$

DELIMITER ;

UPDATE READERS SET FIRSTNAME = 'Maryla'
WHERE READERS.READER_ID = 9;

COMMIT;

SELECT * FROM READERS_AUD;


-- vidoki

CREATE VIEW BOOKS_AND_READERS AS
SELECT RD.READER_ID, RD.FIRSTNAME, RD.LASTNAME, BK.TITLE, RT.RENT_DATE, RT.RETURN_DATE
FROM READERS RD, BOOKS BK, RENTS RT
WHERE RT.BOOK_ID = BK.BOOK_ID
  AND RT.READER_ID = RD.READER_ID
ORDER BY RT.RENT_DATE;

SELECT * FROM BOOKS_AND_READERS;

SHOW PROCESSLIST;

SET GLOBAL EVENT_SCHEDULER=ON;

USE KODILLA_COURSE;           -- [1]

CREATE EVENT UPDATE_VIPS      -- [2]
    ON SCHEDULE EVERY 1 MINUTE -- [3]
    DO CALL UpdateVipLevels(); -- [4]

DROP EVENT UPDATE_VIPS;


-- zadanie 28.5.

USE KODILLA_COURSE;

DROP TABLE IF EXISTS STATS;
DROP VIEW IF EXISTS BESTSELLERS_COUNT;
DROP EVENT IF EXISTS UPDATE_BESTSELLERS_STATS;

CREATE TABLE IF NOT EXISTS STATS  (
    STAT_ID INT(11) NOT NULL AUTO_INCREMENT,
    STAT_DATE DATETIME NOT NULL,
    STAT VARCHAR(20) NOT NULL,
    VALUE INT(11) NOT NULL,
    PRIMARY KEY (STAT_ID)
);

CREATE OR REPLACE VIEW BESTSELLERS_COUNT AS
SELECT SUM(BK.BESTSELLER) AS total_bestsellers
FROM BOOKS BK;

DELIMITER $$
CREATE EVENT IF NOT EXISTS UPDATE_BESTSELLERS_STATS
    ON SCHEDULE EVERY 1 MINUTE
    DO
    BEGIN
        CALL UpdateBestsellers();
        INSERT INTO STATS (STAT_DATE, STAT, VALUE)
        SELECT NOW(), 'BESTSELLERS', total_bestsellers
        FROM BESTSELLERS_COUNT;
    END $$
DELIMITER ;

-- indexy i plany

CREATE TABLE PHONES (
                        PHONE_ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
                        PHONENUM INT(9),
                        FIRSTNAME VARCHAR(50),
                        LASTNAME VARCHAR(50)
);


DELIMITER $$
CREATE PROCEDURE FillTestData()
BEGIN
    DECLARE K INT DEFAULT 0;
    WHILE (K < 100000) DO
            INSERT INTO PHONES (PHONENUM,
                                FIRSTNAME,
                                LASTNAME)
            VALUES(ROUND(RAND()*1000000000),
                   CONCAT('Firstname number ', K),
                   CONCAT('Lastname number ', K));
            IF (MOD(K, 5000) = 0) THEN
                COMMIT;
            END IF;
            SET K = K + 1;
        END WHILE;
    COMMIT;
END $$
DELIMITER ;

CALL FillTestData();


CREATE TABLE PHONESTATS (
                            ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
                            RANGE_FROM INT(11),
                            RANGE_TO INT(11),
                            QUANTITY INT(11)
);


DELIMITER $$
CREATE PROCEDURE CalcPhoneStats()
BEGIN
    DECLARE K INT(11) DEFAULT 0;
    DECLARE QTY INT(11);
    DELETE FROM PHONESTATS;                                    -- [1]
    COMMIT;
    WHILE (K < 100000000) DO
            SELECT COUNT(*)                                         -- [2]
            FROM PHONES                                         -- [3]
            WHERE PHONENUM BETWEEN K-99999 AND K                    -- [4]
            INTO QTY;                                           -- [5]
            INSERT INTO PHONESTATS (RANGE_FROM, RANGE_TO, QUANTITY) -- [6]
            VALUES (K-99999, K, QTY);                           -- [7]
            COMMIT;
            SET K = K + 100000;                                     -- [8]
        END WHILE;
END $$
DELIMITER ;

CALL CalcPhoneStats();

SELECT * FROM PHONESTATS;

EXPLAIN SELECT COUNT(*)
FROM PHONES
WHERE PHONENUM BETWEEN 1 AND 100000;

CREATE INDEX PHONENO ON PHONES (PHONENUM);

-- zadanie 28.6.

EXPLAIN SELECT COUNT(*)
        FROM READERS
        WHERE FIRSTNAME = 'John';

CREATE INDEX BOOKIND ON BOOKS (TITLE);
CREATE INDEX READERSIND ON READERS (FIRSTNAME,LASTNAME);

EXPLAIN SELECT COUNT(*)
        FROM READERS
        WHERE FIRSTNAME = 'John';
