package com.kodilla.rps.GameCore.visualInterface;

import com.kodilla.rps.GameCore.DifficultLevel;
import com.kodilla.rps.GameCore.Figure;
import com.kodilla.rps.GameCore.GameController;
import com.kodilla.rps.GameCore.GameMode;
import com.kodilla.rps.GameCore.generator.FigureSetGenerator;
import com.kodilla.rps.Resources;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

public class Display extends JPanel implements IOnSceneChange {

    private JComboBox FigureComboBox;
    public JPanel MainPanel;
    private JTextPane clueTextPane;
    private JButton fightButton;
    private JPanel statistics;
    private JLabel playerScore;
    private JLabel roundCount;
    private JLabel AIScore;
    private JPanel figureDisplay;
    private JLabel playerFigure;
    private JLabel vs;
    private JLabel AIFigure;
    private JButton newGame;

    FrameManager manager;

    public Display(FrameManager manager) {

        this.manager = manager;
        manager.addToObserverList(this);
        GameController gameController = manager.getGameController();
        Figure[] figures = gameController.getFigures();
        setImage(playerFigure, figures[0].getImagePath());
        gameController.setPlayerFigure(figures[0]);
        Map<String, String> optionAndPath = setComboBoxFiguresDependicies(FigureComboBox, figures);
        clueTextPane.setEditable(false);
        clueTextPane.setFocusable(false);
        clueTextPane.setHighlighter(null);
        updateStats();

        FigureComboBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String chosed = (String) FigureComboBox.getSelectedItem();
                gameController.setPlayerFigure(figures[FigureComboBox.getSelectedIndex()]);
                setImage(playerFigure, optionAndPath.get(chosed));
            }
        });
        newGame.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                manager.showNewGame();
            }
        });
        fightButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                manager.showFightResult();
            }
        });
    }

    private void setImage(JLabel label, String imagePath) {

        Resources.setImage(label, imagePath, 500, 500, this);
    }

    private Map<String, String> setComboBoxFiguresDependicies(JComboBox JCB, Figure[] figures) {
        Map<String, String> map = new HashMap<>();
        JCB.removeAllItems();
        for (Figure figure : figures) {
            JCB.addItem(figure.getName());
            map.put(figure.getName(), figure.getImagePath());
        }
        return map;
    }

    public void setClue() {
        clueTextPane.setText(manager.getGameController().tryToGetClue());
    }

    @Override
    public void onSceneChange() {
        updateStats();
    }

    private void updateStats() {
        playerScore.setText("Player score: " + manager.getGameController().getPlayerScore());
        AIScore.setText("AI score: " + manager.getGameController().getAIScore());
        roundCount.setText("Round: " + manager.getGameController().getCurrentRound() + "/" + manager.getGameController().getRoundCount());
        setClue();
    }

    public JPanel getMainPanel() {
        return MainPanel;
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        MainPanel = new JPanel();
        MainPanel.setLayout(new BorderLayout(0, 0));
        MainPanel.setEnabled(true);
        statistics = new JPanel();
        statistics.setLayout(new GridBagLayout());
        MainPanel.add(statistics, BorderLayout.NORTH);
        playerScore = new JLabel();
        Font playerScoreFont = this.$$$getFont$$$(null, -1, 20, playerScore.getFont());
        if (playerScoreFont != null) playerScore.setFont(playerScoreFont);
        playerScore.setHorizontalAlignment(0);
        playerScore.setHorizontalTextPosition(0);
        playerScore.setText("Player score: ");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        statistics.add(playerScore, gbc);
        roundCount = new JLabel();
        Font roundCountFont = this.$$$getFont$$$(null, -1, 20, roundCount.getFont());
        if (roundCountFont != null) roundCount.setFont(roundCountFont);
        roundCount.setText("Round 1/10");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        statistics.add(roundCount, gbc);
        AIScore = new JLabel();
        Font AIScoreFont = this.$$$getFont$$$(null, -1, 20, AIScore.getFont());
        if (AIScoreFont != null) AIScore.setFont(AIScoreFont);
        AIScore.setHorizontalAlignment(0);
        AIScore.setHorizontalTextPosition(0);
        AIScore.setText("AI score: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        statistics.add(AIScore, gbc);
        newGame = new JButton();
        Font newGameFont = this.$$$getFont$$$(null, -1, 20, newGame.getFont());
        if (newGameFont != null) newGame.setFont(newGameFont);
        newGame.setText("New game");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        statistics.add(newGame, gbc);
        figureDisplay = new JPanel();
        figureDisplay.setLayout(new GridBagLayout());
        MainPanel.add(figureDisplay, BorderLayout.CENTER);
        vs = new JLabel();
        vs.setIcon(new ImageIcon(getClass().getResource("/general/VSWithAlphaChanel150x150.png")));
        vs.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        figureDisplay.add(vs, gbc);
        AIFigure = new JLabel();
        AIFigure.setHorizontalAlignment(4);
        AIFigure.setIcon(new ImageIcon(getClass().getResource("/general/UnknownWithAlphaChanel500x500.png")));
        AIFigure.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        figureDisplay.add(AIFigure, gbc);
        FigureComboBox = new JComboBox();
        Font FigureComboBoxFont = this.$$$getFont$$$(null, -1, 20, FigureComboBox.getFont());
        if (FigureComboBoxFont != null) FigureComboBox.setFont(FigureComboBoxFont);
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Papier");
        defaultComboBoxModel1.addElement("Kamień");
        defaultComboBoxModel1.addElement("Norzyce");
        FigureComboBox.setModel(defaultComboBoxModel1);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        figureDisplay.add(FigureComboBox, gbc);
        clueTextPane = new JTextPane();
        clueTextPane.setEditable(false);
        clueTextPane.setText("clue");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        figureDisplay.add(clueTextPane, gbc);
        fightButton = new JButton();
        Font fightButtonFont = this.$$$getFont$$$(null, -1, 24, fightButton.getFont());
        if (fightButtonFont != null) fightButton.setFont(fightButtonFont);
        fightButton.setText("Fight!");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        figureDisplay.add(fightButton, gbc);
        playerFigure = new JLabel();
        playerFigure.setIcon(new ImageIcon(getClass().getResource("/classic/PaperWithAlphaChanel500x500.png")));
        playerFigure.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        figureDisplay.add(playerFigure, gbc);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MainPanel;
    }

}
