package com.kodilla.rps.GameCore.visualInterface;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.kodilla.rps.GameCore.FightResults;
import com.kodilla.rps.Resources;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Locale;

public class FightResult extends JPanel {
    public JPanel MainPanel;
    private JButton okButton;
    private JLabel simpleResultText;
    private JLabel winnerFigure;
    private JLabel loserFigure;
    private JTextPane FightResultTextPane;

    private FrameManager manager;
    FightResults fightResults;

    public FightResult(FrameManager manager) {

        this.manager = manager;
        $$$setupUI$$$();
        fightResults = manager.getGameController().startFight();
        FightResultTextPane.setEditable(false);
        FightResultTextPane.setFocusable(false);
        FightResultTextPane.setHighlighter(null);
        setScene();
        FightResultTextPane.setContentType("text/html");

        okButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                manager.getGameController().AIMakeMove();
                if(manager.getGameController().getCurrentRound() > manager.getGameController().getRoundCount())
                    manager.showGameOver();
                else manager.backToDisplay();
            }
        });
    }

    private void setScene() {
        String playerFigure = manager.getGameController().getPlayerFigure().getName();
        String AIFigure = manager.getGameController().getAIFigure().getName();

        switch (fightResults) {
            case OVERCOME:
                simpleResultText.setText("You win!");
                setScaledImage(winnerFigure, manager.getGameController().getPlayerFigure().getImagePath(), 500);
                setScaledImage(loserFigure, manager.getGameController().getAIFigure().getImagePath(), 300);
                FightResultTextPane.setText(setFormat(Resources.getRandomWinBattleLog(playerFigure, AIFigure)));
                break;
            case YIELDS:
                simpleResultText.setText("You lose!");
                setScaledImage(winnerFigure, manager.getGameController().getAIFigure().getImagePath(), 500);
                setScaledImage(loserFigure, manager.getGameController().getPlayerFigure().getImagePath(), 300);
                FightResultTextPane.setText(setFormat(Resources.getRandomLoseBattleLog(AIFigure, playerFigure)));
                break;
            case TIES:
                simpleResultText.setText("Tie!");
                setScaledImage(winnerFigure, manager.getGameController().getPlayerFigure().getImagePath(), 500);
                setScaledImage(loserFigure, manager.getGameController().getAIFigure().getImagePath(), 500);
                FightResultTextPane.setText(setFormat(Resources.getRandomTieBattleLog(playerFigure, AIFigure)));
                break;
        }
    }

    private String setFormat(String tekst) {
        return "<html><body style='text-align: center; font-family: sans-serif;'>" +
                "<div style='font-size: 24px; font-weight: bold;'>" + tekst + "</div>" +
                "</body></html>";
    }

    private void setScaledImage(JLabel label, String path, int size) {
        Resources.setImage(label,path,size,size,this);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        MainPanel = new JPanel();
        MainPanel.setLayout(new GridBagLayout());
        okButton = new JButton();
        Font okButtonFont = this.$$$getFont$$$(null, -1, 28, okButton.getFont());
        if (okButtonFont != null) okButton.setFont(okButtonFont);
        okButton.setText("Ok!");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        MainPanel.add(okButton, gbc);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.BOTH;
        MainPanel.add(panel1, gbc);
        winnerFigure = new JLabel();
        winnerFigure.setIcon(new ImageIcon(getClass().getResource("/general/UnknownWithAlphaChanel500x500.png")));
        winnerFigure.setText("");
        panel1.add(winnerFigure, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        loserFigure = new JLabel();
        loserFigure.setIcon(new ImageIcon(getClass().getResource("/general/UnknownWithAlphaChanel500x500.png")));
        loserFigure.setText("");
        panel1.add(loserFigure, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        simpleResultText = new JLabel();
        Font simpleResultTextFont = this.$$$getFont$$$(null, -1, 48, simpleResultText.getFont());
        if (simpleResultTextFont != null) simpleResultText.setFont(simpleResultTextFont);
        simpleResultText.setText("Wygrana!");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        MainPanel.add(simpleResultText, gbc);
        FightResultTextPane = new JTextPane();
        FightResultTextPane.setContentType("text/html");
        FightResultTextPane.setEditable(false);
        FightResultTextPane.setEnabled(true);
        Font FightResultTextPaneFont = this.$$$getFont$$$(null, -1, 26, FightResultTextPane.getFont());
        if (FightResultTextPaneFont != null) FightResultTextPane.setFont(FightResultTextPaneFont);
        FightResultTextPane.setMargin(new Insets(3, 3, 3, 3));
        FightResultTextPane.setOpaque(false);
        FightResultTextPane.setPreferredSize(new Dimension(1000, 120));
        FightResultTextPane.setText("<html>\r  <head>\r    \r  </head>\r  <body>\r    Witaj moj mily\r  </body>\r</html>\r");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        MainPanel.add(FightResultTextPane, gbc);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MainPanel;
    }

}
