package com.kodilla.rps.GameCore.visualInterface;

import com.kodilla.rps.Resources;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Locale;

public class GameOver extends JPanel {
    public JPanel MainPanel;
    private JLabel endImage;
    private JLabel endText;
    private JButton newGameButton;
    private JButton EndGameButton;

    private FrameManager manager;

    public GameOver(FrameManager manager) {
        this.manager = manager;

        if (manager.getGameController().getPlayerScore() > manager.getGameController().getAIScore()) {
            endText.setText("Congratulations! You won!");
            Resources.setImage(endImage, "/general/WinImageWithAlphaChanel.png", 500, 500, this);
        } else if (manager.getGameController().getPlayerScore() < manager.getGameController().getAIScore()) {
            endText.setText("Congratulations! You lose!");
            Resources.setImage(endImage, "/general/LoseImageWithAlphaChanel.png", 500, 500, this);
        } else {
            endText.setText("Congratulations! You won tie!");
            Resources.setImage(endImage, "/general/TieImageWithAlphaChanel.png", 500, 500, this);
        }

        newGameButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                manager.showNewGame();
            }
        });
        EndGameButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.exit(0);
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        MainPanel = new JPanel();
        MainPanel.setLayout(new GridBagLayout());
        endImage = new JLabel();
        endImage.setIcon(new ImageIcon(getClass().getResource("/general/UnknownWithAlphaChanel500x500.png")));
        endImage.setText("");
        endImage.setVerticalAlignment(1);
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        MainPanel.add(endImage, gbc);
        endText = new JLabel();
        Font endTextFont = this.$$$getFont$$$(null, -1, 28, endText.getFont());
        if (endTextFont != null) endText.setFont(endTextFont);
        endText.setHorizontalAlignment(0);
        endText.setHorizontalTextPosition(0);
        endText.setText("Gratulacje! Przegrałeś!");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        MainPanel.add(endText, gbc);
        newGameButton = new JButton();
        Font newGameButtonFont = this.$$$getFont$$$(null, -1, 28, newGameButton.getFont());
        if (newGameButtonFont != null) newGameButton.setFont(newGameButtonFont);
        newGameButton.setText("New game");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        MainPanel.add(newGameButton, gbc);
        EndGameButton = new JButton();
        Font EndGameButtonFont = this.$$$getFont$$$(null, -1, 28, EndGameButton.getFont());
        if (EndGameButtonFont != null) EndGameButton.setFont(EndGameButtonFont);
        EndGameButton.setText("Exit");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        MainPanel.add(EndGameButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MainPanel;
    }

}
