package com.kodilla.rps.GameCore.visualInterface;

import com.kodilla.rps.GameCore.DifficultLevel;
import com.kodilla.rps.GameCore.Figure;
import com.kodilla.rps.GameCore.GameMode;
import com.kodilla.rps.GameCore.generator.FigureSetGenerator;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

public class NewGame extends JPanel {
    public JPanel MainPanel;
    private JComboBox gameModeComboBox;
    private JComboBox difficultComboBox;
    private JSpinner roundCount;
    private JButton startButton;

    private FrameManager manager;

    public NewGame(FrameManager manager) {
        this.manager = manager;

        // setVisible(true);
        roundCount.setModel(new SpinnerNumberModel(1, 1, 99, 1));

        Map<String, DifficultLevel> comboBoxDifficultDependicies = setComboBoxDifficult();
        Map<String, GameMode> comboBoxGameModeDependicies = setComboBoxGameMode();

        startButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                int rounds = (int) roundCount.getValue();
                DifficultLevel dif = comboBoxDifficultDependicies.get((String) difficultComboBox.getSelectedItem());
                GameMode gm = comboBoxGameModeDependicies.get((String) gameModeComboBox.getSelectedItem());
                manager.startGame(rounds, gm, dif);
            }
        });
    }

    private Map<String, DifficultLevel> setComboBoxDifficult() {
        Map<String, DifficultLevel> map = new HashMap<>();
        difficultComboBox.removeAllItems();
        for (DifficultLevel dl : DifficultLevel.values()) {
            difficultComboBox.addItem(dl.toString().replaceAll("_", " ").toLowerCase());
            map.put(dl.toString().replaceAll("_", " ").toLowerCase(), dl);
        }
        return map;
    }

    private Map<String, GameMode> setComboBoxGameMode() {
        Map<String, GameMode> map = new HashMap<>();
        gameModeComboBox.removeAllItems();
        for (GameMode gm : GameMode.values()) {
            gameModeComboBox.addItem(gm.toString().replaceAll("_", " ").toLowerCase());
            map.put(gm.toString().replaceAll("_", " ").toLowerCase(), gm);
        }
        return map;
    }

    public JPanel getMainPanel() {
        return MainPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        MainPanel = new JPanel();
        MainPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$(null, -1, 20, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setText("Game mode:");
        MainPanel.add(label1);
        gameModeComboBox = new JComboBox();
        Font gameModeComboBoxFont = this.$$$getFont$$$(null, -1, 20, gameModeComboBox.getFont());
        if (gameModeComboBoxFont != null) gameModeComboBox.setFont(gameModeComboBoxFont);
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Classic game");
        defaultComboBoxModel1.addElement("Pokemon game");
        defaultComboBoxModel1.addElement("Pokemon+");
        defaultComboBoxModel1.addElement("Multiverse");
        gameModeComboBox.setModel(defaultComboBoxModel1);
        MainPanel.add(gameModeComboBox);
        final JLabel label2 = new JLabel();
        Font label2Font = this.$$$getFont$$$(null, -1, 20, label2.getFont());
        if (label2Font != null) label2.setFont(label2Font);
        label2.setText("Difficult:");
        MainPanel.add(label2);
        difficultComboBox = new JComboBox();
        Font difficultComboBoxFont = this.$$$getFont$$$(null, -1, 20, difficultComboBox.getFont());
        if (difficultComboBoxFont != null) difficultComboBox.setFont(difficultComboBoxFont);
        final DefaultComboBoxModel defaultComboBoxModel2 = new DefaultComboBoxModel();
        defaultComboBoxModel2.addElement("Łatwy");
        defaultComboBoxModel2.addElement("Normalny");
        defaultComboBoxModel2.addElement("Nienormalny");
        difficultComboBox.setModel(defaultComboBoxModel2);
        MainPanel.add(difficultComboBox);
        final JLabel label3 = new JLabel();
        Font label3Font = this.$$$getFont$$$(null, -1, 20, label3.getFont());
        if (label3Font != null) label3.setFont(label3Font);
        label3.setText("Round count:");
        MainPanel.add(label3);
        roundCount = new JSpinner();
        Font roundCountFont = this.$$$getFont$$$(null, -1, 20, roundCount.getFont());
        if (roundCountFont != null) roundCount.setFont(roundCountFont);
        MainPanel.add(roundCount);
        startButton = new JButton();
        Font startButtonFont = this.$$$getFont$$$(null, -1, 26, startButton.getFont());
        if (startButtonFont != null) startButton.setFont(startButtonFont);
        startButton.setText("Start!");
        MainPanel.add(startButton);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MainPanel;
    }


}
