INSERT INTO POSTS(ID, USER_ID, BODY)
VALUES (6,1,'SOMETHING');
INSERT INTO POSTS(ID, USER_ID, BODY)
VALUES (7,1,'CHICKEN');
INSERT INTO POSTS(ID, USER_ID, BODY)
VALUES (8,1,'YES SIR');
COMMIT;

UPDATE POSTS
SET BODY = 'TO DELETE'
WHERE ID = 6;
UPDATE POSTS
SET BODY = 'TO DELETE'
WHERE ID = 7;
UPDATE POSTS
SET BODY = 'TO DELETE'
WHERE ID = 8;
COMMIT;

DELETE FROM POSTS
WHERE ID = 6;
DELETE FROM POSTS
WHERE ID = 7;
DELETE FROM POSTS
WHERE ID = 8;
COMMIT;
